Product details
OmarAbdelgilil/Elevate_Ecommerce pull request #13
Opened 2024-11-25 19:38 UTC by faridatarek

2024-11-25 21:43 UTC, OmarAbdelgilil commented on lib/core/widgets/custom_appbar.dart
why still using this appbar ?

2024-11-25 21:46 UTC, OmarAbdelgilil commented on lib/features/home/presentation/product_details_screen/product_details_view/product_details_screen.dart
still using builder ?

2024-11-25 21:48 UTC, Abdalla-Eldaly approved these changes
great job

2024-11-25 21:48 UTC, Abdalla-Eldaly commented on lib/core/widgets/custom_button.dart
use AppTextStyles

2024-11-25 21:49 UTC, OmarAbdelgilil commented on lib/features/home/presentation/product_widget/product_view_model/product_view_model.dart
this wasn't your task I think

2024-11-25 21:50 UTC, OmarAbdelgilil requested changes
take a look at the comments - too much conflicts are u sure u pulled dev branch

2024-11-26 01:07 UTC, Menna1311 approved these changes
great job

2024-11-26 10:23 UTC, OmarAbdelgilil approved these changes
Well done ! 👏

2024-11-26 19:11 UTC, merged